services:
  db:
    image: "mysql:${MYSQL_VERSION}"          # Usa la versión definida en .env
    container_name: wp_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./database/initdb:/docker-entrypoint-initdb.d # Used for initializing the database with custom scripts
    ports:
      - "33060:3306"                        # Expose on localhost:33060
    networks:
      - wp-net

  wordpress:
    image: "wordpress:${WORDPRESS_VERSION}"  # Usa la versión definida en .env
    user: "${LOCAL_UID}:${LOCAL_GID}" 
    container_name: wp_app
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    
    volumes:
      - ./wordpress:/var/www/html           # Mounts the local 'wordpress' directory to '/var/www/html' in the container for real-time synchronization of WordPress code changes during development
    ports:
      - "8000:80"                            # Expose on localhost:8000
    networks:
      - wp-net
networks:
  wp-net:
    driver: bridge                          # Isolated bridge network
volumes:
  db_data:
